apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/Sooria16/knote.git
    targetRevision: main
    path: kube-cluster/dev/multi-tier
  destination: 
    server: https://kubernetes.default.svc
    namespace: devproject

  syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
  ignoreDifferences:
  - group: batch
    kind: Job
    name: ingress-nginx-admission-patch
    namespace: ingress-nginx
  - group: batch
    kind: Job
    name: ingress-nginx-admission-create
    namespace: ingress-nginx
  

