apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: webapp-ingress
  namespace: devproject
  annotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - www.cipherworld.shop
      secretName: webapp-tls
  rules:
    - host: www.cipherworld.shop
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: websvc
                port:
                  number: 80

